site_name: HuFo System

theme:
    name: readthedocs
    highlightjs: true

docs:
    ../graphics/
      hufo_flow_1.png

nav:
    - Back to Project Page: https://hvc.berlin/projects/hufo-listening-room/
    - User Guide (Reaper): reaper.md
    - SuperCollider: supercollider.md
    - OSC Router: oscrouter.md
    - Signal Flow: signalflow.md
    - System Setup: system_setup.md
