site_name: HuFo System

theme:
    name: material
    highlightjs: true
    logo: graphics/interface_HVC_small.png

extra:
    generator: false

docs:
    ../graphics/
      hufo_flow_1.png

nav:
    - Back to Project Page: https://hvc.berlin/projects/hufo-listening-room/
    - Reaper User Guide: reaper.md
    - SuperCollider: supercollider.md
    - OSC Router: oscrouter.md
    - Signal Flow: signalflow.md
    - System Setup: system_setup.md
